name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" > api_key.txt

      - name: Use API Key in Your App
        run: node your_script.js
